# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: gaocegege
          template: classic
          base: header, activity, metadata
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_notable: yes
          plugin_projects: yes
          plugin_projects_limit: 4
          plugin_rss: yes
          plugin_rss_source: http://gaocegege.com/Blog/rss.xml
          plugin_rss_limit: 4
