# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: gaocegege
          template: classic
          base: header
          config_timezone: Asia/Shanghai
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7                                   # Display last week stats
          plugin_wakatime_sections: time, editors-graphs, os-graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: https://dev.gaocegege.com:3000                 # Wakatime url endpoint
          plugin_wakatime_user: .user.login                         # User
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_notable: yes
          plugin_rss: yes
          plugin_rss_source: http://gaocegege.com/Blog/rss.xml
          plugin_rss_limit: 4
